name: Sync Files
on:
  push:
    paths:
      - 'data/**'
    branches:
      - main
  workflow_dispatch:
jobs:
  sync:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@main

      - name: Run GitHub File Sync
        uses: BetaHuhn/repo-file-sync-action@v1.21.1
        with:
          GH_PAT: ${{ secrets.GH_PAT }}
